/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import DC.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author XtianDR
 */
public class AccountRecover extends javax.swing.JDialog {
    Login a;
    private String username;
    private String date;
    private String answer;
    private String question;
    /**
     * Creates new form AccountRecover
     */
    public AccountRecover(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mainpanel.removeAll();
        mainpanel.add(p1);
        mainpanel.repaint();
        mainpanel.revalidate();
    }
    public AccountRecover(java.awt.Frame parent, boolean modal, Login a) {
        super(parent, modal);
        initComponents();
        this.a = a;
        mainpanel.removeAll();
        mainpanel.add(p1);
        mainpanel.repaint();
        mainpanel.revalidate();
    }
    void getUserData(String username){
        boolean suc = false;
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps, ps1;
            ResultSet rs;
            ps = c.prepareStatement("Select * from account");
            rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString(1).equals(this.txt_un.getText())) {
                    setDate(rs.getString(5));
                    setQuestion(rs.getString(8));
                    setAnswer(rs.getString(9));
                    mainpanel.removeAll();
                    mainpanel.add(p2);
                    mainpanel.repaint();
                    mainpanel.revalidate();
                    //ps1 = c.prepareStatement("INSERT INTO logs (user,lvl,actn,dati,info) VALUES" + "('" + this.getUser()+ "','" +this.getLevel()+ "','Login',DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S'), 'The user login to the system successfully.')");
                    //ps1.execute();
                    suc = false;
                    break;
                } else {
                    suc = true;
                }
            }
            if (suc) {
                JOptionPane.showMessageDialog(this, "'"+txt_un.getText()+"' not Found!\nMake sure this username is\nregistered to the system.", "Account Recovery", JOptionPane.ERROR_MESSAGE);
                txt_un.setText("");
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_un = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_date = new com.toedter.calendar.JCalendar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_question = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_answer = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_cpw = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        txt_pw = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        txt_w = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        p6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account Recovery");

        mainpanel.setLayout(new java.awt.CardLayout());

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Username:");
        p1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 20));

        txt_un.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p1.add(txt_un, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 193, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("your account to access the system.");
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("are the owner of the account.");
        p1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("If you forgot your password, you must recover");
        p1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("We asking some question to verify that you");
        p1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 20));

        mainpanel.add(p1, "card2");

        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("When did you create this account?");
        p2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        p2.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 160));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("VERIFY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 80, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("I DON'T KNOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        mainpanel.add(p2, "card2");

        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Answer:");
        p3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("When you created this account, you select a");
        p3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setText("(ALL UPPERCASE LETTERS)");
        p3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 210, 20));

        txt_question.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p3.add(txt_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Question:");
        p3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txt_answer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        p3.add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("I DON'T KNOW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        p3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("VERIFY");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("recovery question to recover your account.");
        p3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("You must answer the question properly.");
        p3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 20));

        mainpanel.add(p3, "card2");

        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("RE-ENTER NEW PASSWORD:");
        p4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("We recommended to create your new");
        p4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("password and make sure to remember it ");
        p4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("to prevent this case.");
        p4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 20));
        p4.add(txt_cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("ENTER NEW PASSWORD:");
        p4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 20));
        p4.add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("CHANGE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        p4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 100, 30));

        txt_w.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txt_w.setForeground(java.awt.Color.red);
        p4.add(txt_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 20));

        mainpanel.add(p4, "card2");

        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("to retrieve/recover your account.");
        p5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 260, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Sorry! Failed to recover your account");
        p5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("this account. We recommended to make new");
        p5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("account or ask for the developer of this system");
        p5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("We did not verify that you are the owner of");
        p5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 20));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("CLOSE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        p5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 193, 80, 30));

        mainpanel.add(p5, "card2");

        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Finished Recover your account");
        p6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Congratulations!\nYou successfully recover your account.\nIf the recovery is sucess, login to the system\nwith the new password.");
        jTextArea1.setOpaque(false);
        p6.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 150));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("CLOSE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        p6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, 30));

        mainpanel.add(p6, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getUserData(txt_un.getText());
        setUsername(txt_un.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.add(p5);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (getDate().equals((String) dateFormat.format(txt_date.getDate()))){
            JOptionPane.showMessageDialog(this, "Verify Success!", "Account Recovery", JOptionPane.INFORMATION_MESSAGE);
            mainpanel.removeAll();
            mainpanel.add(p4);
            mainpanel.repaint();
            mainpanel.revalidate();
        } else {
            JOptionPane.showMessageDialog(this, "The date you give is not match!\nPlease Try Again.", "Account Recovery", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.add(p3);
        mainpanel.repaint();
        mainpanel.revalidate();
        txt_question.setText(this.getQuestion());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (txt_pw.getText().isEmpty()){
            txt_w.setText("*Password is required!");
        } else if (txt_pw.getText().length()<5){
            txt_w.setText("*Password have at least 5 character!");
        } else if (txt_cpw.getText().isEmpty()){
            txt_w.setText("*Please re-enter your new password!");
        } else if (!txt_cpw.getText().equals(txt_pw.getText())){
            txt_w.setText("*Password not match!");
            txt_pw.setText("");
            txt_cpw.setText("");
        } else {
            txt_w.setText("");
            try {
                DBConnection.init();
                Connection c = (Connection) DBConnection.getConnection();
                PreparedStatement ps, ps1;
                ps = c.prepareStatement("Update account set user =(?), pass =(?) where user like (?)");
                ps.setString(1, getUsername());
                ps.setString(2, txt_pw.getText());
                ps.setString(3, getUsername());
                //ps1 = c.prepareStatement("INSERT INTO logs (user,lvl,actn,dati,info) VALUES" + "('" + this.a.a.a.getUser() + "','" +this.a.a.a.getLevel()+ "','Update Event',DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S'), 'The user updated event to the system.')");
                int n = JOptionPane.showConfirmDialog(this, "Do you want to continue?\nMake sure you remember this password.", "Confirm Change Password", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    ps.executeUpdate();
                    //ps1.execute();
                    JOptionPane.showMessageDialog(this, "Password Change");
                    mainpanel.removeAll();
                    mainpanel.add(p6);
                    mainpanel.repaint();
                    mainpanel.revalidate();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (getAnswer().equals(txt_answer.getText())){
            JOptionPane.showMessageDialog(this, "Verify Success!", "Account Recovery", JOptionPane.INFORMATION_MESSAGE);
            mainpanel.removeAll();
            mainpanel.add(p4);
            mainpanel.repaint();
            mainpanel.revalidate();
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect Answer!\nPlease Try Again.", "Account Recovery", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountRecover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccountRecover dialog = new AccountRecover(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JTextField txt_answer;
    private javax.swing.JPasswordField txt_cpw;
    private com.toedter.calendar.JCalendar txt_date;
    private javax.swing.JPasswordField txt_pw;
    private javax.swing.JLabel txt_question;
    private javax.swing.JTextField txt_un;
    private javax.swing.JLabel txt_w;
    // End of variables declaration//GEN-END:variables

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
