/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import DC.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class Account extends javax.swing.JInternalFrame {
    Main a;
    DefaultTableModel model1 = new DefaultTableModel();
    String username;
    /**
     * Creates new form Purok
     */
    public Account() {
        initComponents();
        model1 = (DefaultTableModel) tb_account.getModel();
        LoadAccount();
    }
    
    public Account(Main a) {
        initComponents();
        this.a = a;
        model1 = (DefaultTableModel) tb_account.getModel();
        LoadAccount();
    }
    
    public void LoadAccount() {
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date d;
            ps = c.prepareStatement("Select * from account");
            rs = ps.executeQuery();
            model1.setRowCount(0);
            while (rs.next()) {
                try {
                    d = dateFormat.parse(rs.getString(7));
                    SimpleDateFormat dat = new SimpleDateFormat("MMMM dd, yyyy");
                    model1.addRow(new Object[]{rs.getString(5) + " " + rs.getString(6) + " " + rs.getString(4), rs.getString(1), rs.getString(3), dat.format(d)});
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_account = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_account.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Level", "Date Registered"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_account.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_accountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_account);
        if (tb_account.getColumnModel().getColumnCount() > 0) {
            tb_account.getColumnModel().getColumn(0).setResizable(false);
            tb_account.getColumnModel().getColumn(1).setResizable(false);
            tb_account.getColumnModel().getColumn(2).setResizable(false);
            tb_account.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 990, 520));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Remove User Male_20px.png"))); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Add User Male_20px.png"))); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Change User Male_20px.png"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (username == null){
            JOptionPane.showMessageDialog(this, "Sorry! You have not select one of the account in the table.", "Update Account", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                DBConnection.init();
                Connection c = (Connection) DBConnection.getConnection();
                PreparedStatement ps, ps1;
                ps = c.prepareStatement("Delete from account where user=(?)");
                ps.setString(1, username);
                //ps1 = c.prepareStatement("INSERT INTO logs (user,lvl,actn,dati,info) VALUES" + "('" + this.a.a.getUser() + "','" +this.a.a.getLevel()+ "','Delete People',DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S'), 'The user deleted people to the system.')");
                int n = JOptionPane.showConfirmDialog(null, "Do you want to delete this account?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    ps.executeUpdate();
                    //ps1.execute();
                    JOptionPane.showMessageDialog(null, "Account Delete!");
                    LoadAccount();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UpdateUserLevel ab = new UpdateUserLevel(new javax.swing.JFrame(), true, this);
        ab.setLocationRelativeTo(this.a);
        ab.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AddUser b = new AddUser(new javax.swing.JFrame(), true, this);
        b.setLocationRelativeTo(this.a);
        b.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_accountMouseClicked
        // TODO add your handling code here:
        username = String.valueOf(model1.getValueAt(tb_account.getSelectedRow(), 1));
    }//GEN-LAST:event_tb_accountMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_account;
    // End of variables declaration//GEN-END:variables
}
