/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import DC.DBConnection;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class AddUser extends javax.swing.JDialog {
    Image img = (new ImageIcon(getClass().getResource("/Misc/null.png"))).getImage();
    Account a;

    /**
     * Creates new form AddAccount
     */
    public AddUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AddUser(java.awt.Frame parent, boolean modal, Account a) {
        super(parent, modal);
        initComponents();
        this.a = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_mi = new javax.swing.JTextField();
        txt_fn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ln = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_un = new javax.swing.JTextField();
        cb_lvl = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_rq = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_ra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_cpw = new javax.swing.JPasswordField();
        txt_pw = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        txt_w = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account");
        setIconImage(img);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("LEVEL:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        txt_mi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_mi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 50, -1));

        txt_fn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("M. I.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NAME:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txt_ln.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ACCOUNT RECOVERY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 410, 20));

        txt_un.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_un, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, -1));

        cb_lvl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_lvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECT YOUR LEVEL---", "Administrator", "Treasurer", "Secretary", "User" }));
        jPanel1.add(cb_lvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("RECOVERY ANSWER:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("USER INFORMATION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 10, 410, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("CONFIRM PASSWORD:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 20));

        cb_rq.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_rq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT RECOVERY QUESTION--", "What is your favorite color?", "What is your father's middle name?", "Who is your favorite actor, singer or artist?", "What was the name of your high school?" }));
        jPanel1.add(cb_rq, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 260, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("RECOVERY QUESTION:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        txt_ra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 260, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("Note: Username and password have at least 5 and not more than 8 character");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 410, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Cancel_20px.png"))); // NOI18N
        jButton1.setText("CANCEL");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("This account recovery helps you to recover your account if you \nforgot your  password. You must choose the question that you\nnever forget. If you forgot the answers in recover your account,\nyou must contact the developer of this software or ask your\nadministrator to recreate your account.");
        jTextArea2.setBorder(null);
        jTextArea2.setOpaque(false);
        jPanel1.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 400, 80));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("USERNAME:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ENTER PASSWORD:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 20));

        txt_cpw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));

        txt_pw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 131, 180, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Ok_20px.png"))); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 90, -1));

        txt_w.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txt_w.setForeground(java.awt.Color.red);
        jPanel1.add(txt_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setText("Note: Your recovery answer must in UPPERCASE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 400, 20));

        jCheckBox1.setToolTipText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Show Password_15px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String mi;
        if (txt_ln.getText().isEmpty()) {
            txt_w.setText("*Last Name is required.");
        } else if (txt_fn.getText().isEmpty()) {
            txt_w.setText("*First Name is required.");
        } else if (txt_un.getText().isEmpty()) {
            txt_w.setText("*Username is required.");
        } else if (txt_un.getText().length()<4) {
            txt_w.setText("*Username have at least 5 character.");
        } else if (cb_lvl.getSelectedIndex()==0) {
            txt_w.setText("*Select your level.");
        } else if (txt_pw.getText().isEmpty()) {
            txt_w.setText("*Password is required!");
        } else if (txt_pw.getText().length()<4) {
            txt_w.setText("*Password have at least 5 character.");
        } else if (txt_cpw.getText().isEmpty()) {
            txt_w.setText("*Please re-enter your new password.");
        } else if (!txt_pw.getText().equals(txt_cpw.getText())) {
            txt_w.setText("*Password not match.");
            txt_cpw.setText("");
        } else if (cb_rq.getSelectedIndex()==0) {
            txt_w.setText("*Select a recovery question.");
        } else if (txt_ra.getText().isEmpty()) {
            txt_w.setText("*Recovery answer is required.");
        } else {
            txt_w.setText("");
            try {
                if (txt_mi.getText().isEmpty()) {
                    mi = "";
                } else {
                    mi = txt_mi.getText() + ".";
                }
                DBConnection.init();
                Connection c = (Connection) DBConnection.getConnection();
                PreparedStatement ps;
                ps = c.prepareStatement("Insert into account (user,pass,lvl, ln, fn, mi, dacr, requ, rean) values ('" + txt_un.getText() + "','" + txt_pw.getText() + "','" + (String) cb_lvl.getSelectedItem() + "','" + txt_ln.getText() + "','" + txt_fn.getText() + "','" + mi + "',DATE_FORMAT(NOW(),'%Y-%m-%d'),'" + (String) cb_rq.getSelectedItem() + "','" + txt_ra.getText() + "')");
                int n = JOptionPane.showConfirmDialog(this, "Do you want to add this account?", "Confirm Add", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    ps.execute();
                    JOptionPane.showMessageDialog(this, "Account Added!");
                    dispose();
                    this.a.LoadAccount();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            this.txt_pw.setEchoChar((char) 0);
            this.txt_cpw.setEchoChar((char) 0);
        } else {
            this.txt_pw.setEchoChar('\u25cf');
            this.txt_cpw.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUser dialog = new AddUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_lvl;
    private javax.swing.JComboBox<String> cb_rq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPasswordField txt_cpw;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_ln;
    private javax.swing.JTextField txt_mi;
    private javax.swing.JPasswordField txt_pw;
    private javax.swing.JTextField txt_ra;
    private javax.swing.JTextField txt_un;
    private javax.swing.JLabel txt_w;
    // End of variables declaration//GEN-END:variables
}
