/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Main extends javax.swing.JFrame {
    
    Login a;
    Image img = (new ImageIcon(getClass().getResource("/Misc/BHIS.png"))).getImage();


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        UserHome frame = new UserHome();
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }

    public Main(Login a) {
        initComponents();
        this.a = a;
        UserHome frame = new UserHome();
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
        LoadUserInfo();
        LoadLevel(this.a.getLevel());
        
    }
    Connection OpenDatabaseConnection() {
        Connection c = null;

        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/barangayhall", "root", "root");

        } catch (Exception e) {
            System.out.println(e);
        }
        return c;
    }
    void LoadUserInfo(){
        this.txt_user.setText(this.a.getName() + "(" + this.a.getUser() +")");
        this.txt_level.setText(this.a.getLevel());
    }
    
    void LoadLevel(String level){
        if (level.equals("Treasurer")) {
            tb_doc.setEnabled(false);
            tb_people.setEnabled(false);
            tb_event.setEnabled(false);
            mi_manageacc.setEnabled(false);
        } else if (level.equals("Secretary")){
            tb_budget.setEnabled(false);
            mi_manageacc.setEnabled(false);
        } else {
            
        }
    }
    
    void Logout(){
        int option = JOptionPane.showConfirmDialog(this , "Do you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION){
            a = new Login();
            this.dispose();
            a.setVisible(true);
        }
    }
    void About(){
        About e = new About(new javax.swing.JFrame(), true);
        e.setLocationRelativeTo(this.a);
        e.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        tb_home = new javax.swing.JButton();
        tb_people = new javax.swing.JButton();
        tb_officials = new javax.swing.JButton();
        tb_budget = new javax.swing.JButton();
        tb_event = new javax.swing.JButton();
        tb_doc = new javax.swing.JButton();
        tb_logs = new javax.swing.JButton();
        tb_logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        txt_level = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_manageacc = new javax.swing.JMenuItem();
        mi_logout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_syswiz = new javax.swing.JMenuItem();
        mi_changepass = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mi_help = new javax.swing.JMenuItem();
        mi_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[BHIS] Barangay Hall Information System");
        setIconImage(img);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        tb_home.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Home_48px.png"))); // NOI18N
        tb_home.setText("HOME");
        tb_home.setBorder(null);
        tb_home.setFocusable(false);
        tb_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_home.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_home.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_home.setOpaque(false);
        tb_home.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_homeMouseExited(evt);
            }
        });
        tb_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_homeActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_home);

        tb_people.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_people.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Conference_48px.png"))); // NOI18N
        tb_people.setText("PEOPLE");
        tb_people.setBorder(null);
        tb_people.setFocusable(false);
        tb_people.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_people.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_people.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_people.setOpaque(false);
        tb_people.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_people.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_people.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_peopleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_peopleMouseExited(evt);
            }
        });
        tb_people.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_peopleActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_people);

        tb_officials.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_officials.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Manager_48px.png"))); // NOI18N
        tb_officials.setText("OFFICIALS");
        tb_officials.setBorder(null);
        tb_officials.setFocusable(false);
        tb_officials.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_officials.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_officials.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_officials.setOpaque(false);
        tb_officials.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_officials.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_officials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_officialsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_officialsMouseExited(evt);
            }
        });
        tb_officials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_officialsActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_officials);

        tb_budget.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_budget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Money Bag_48px.png"))); // NOI18N
        tb_budget.setText("BUDGET");
        tb_budget.setBorder(null);
        tb_budget.setFocusable(false);
        tb_budget.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_budget.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_budget.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_budget.setOpaque(false);
        tb_budget.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_budget.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_budget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_budgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_budgetMouseExited(evt);
            }
        });
        tb_budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_budgetActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_budget);

        tb_event.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Calendar_48px.png"))); // NOI18N
        tb_event.setText("EVENT");
        tb_event.setBorder(null);
        tb_event.setFocusable(false);
        tb_event.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_event.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_event.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_event.setOpaque(false);
        tb_event.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_event.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_eventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_eventMouseExited(evt);
            }
        });
        tb_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_eventActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_event);

        tb_doc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Document_48px.png"))); // NOI18N
        tb_doc.setText("DOCUMENT");
        tb_doc.setBorder(null);
        tb_doc.setFocusable(false);
        tb_doc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_doc.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_doc.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_doc.setOpaque(false);
        tb_doc.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_doc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_docMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_docMouseExited(evt);
            }
        });
        tb_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_docActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_doc);

        tb_logs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_logs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Edit Property_48px.png"))); // NOI18N
        tb_logs.setText("LOGS");
        tb_logs.setBorder(null);
        tb_logs.setFocusable(false);
        tb_logs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_logs.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_logs.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_logs.setOpaque(false);
        tb_logs.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_logs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_logs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_logsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_logsMouseExited(evt);
            }
        });
        tb_logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_logsActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_logs);

        tb_logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Close Window_48px.png"))); // NOI18N
        tb_logout.setText("LOGOUT");
        tb_logout.setBorder(null);
        tb_logout.setFocusable(false);
        tb_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_logout.setMaximumSize(new java.awt.Dimension(90, 75));
        tb_logout.setMinimumSize(new java.awt.Dimension(90, 75));
        tb_logout.setOpaque(false);
        tb_logout.setPreferredSize(new java.awt.Dimension(90, 75));
        tb_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tb_logoutMouseExited(evt);
            }
        });
        tb_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tb_logout);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("LEVEL:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, -1, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USER:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        txt_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 222, 20));

        txt_level.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -1, 150, 20));

        jDesktopPane1.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 579, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Account");

        mi_manageacc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mi_manageacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Contact Card_15px.png"))); // NOI18N
        mi_manageacc.setText("Manage Accounts (Administrator)");
        mi_manageacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_manageaccActionPerformed(evt);
            }
        });
        jMenu1.add(mi_manageacc);

        mi_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mi_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Close Window_15px.png"))); // NOI18N
        mi_logout.setText("Logout");
        mi_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_logoutActionPerformed(evt);
            }
        });
        jMenu1.add(mi_logout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        mi_syswiz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mi_syswiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Tree Structure_15px.png"))); // NOI18N
        mi_syswiz.setText("System Wizard");
        jMenu2.add(mi_syswiz);

        mi_changepass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mi_changepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Password_15px.png"))); // NOI18N
        mi_changepass.setText("Account Settings");
        mi_changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_changepassActionPerformed(evt);
            }
        });
        jMenu2.add(mi_changepass);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        mi_help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mi_help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Help_15px.png"))); // NOI18N
        mi_help.setText("Help");
        jMenu3.add(mi_help);

        mi_about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mi_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Info_15px.png"))); // NOI18N
        mi_about.setText("About");
        mi_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_aboutActionPerformed(evt);
            }
        });
        jMenu3.add(mi_about);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_logoutActionPerformed
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_mi_logoutActionPerformed

    private void tb_peopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_peopleActionPerformed
        // TODO add your handling code here:
        People frame = new People(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_peopleActionPerformed

    private void tb_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_homeActionPerformed
        // TODO add your handling code here:
        UserHome frame = new UserHome();
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_homeActionPerformed

    private void tb_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_homeMouseEntered
        // TODO add your handling code here:
        tb_home.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_homeMouseEntered

    private void tb_peopleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_peopleMouseExited
        // TODO add your handling code here:
        tb_people.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_peopleMouseExited

    private void tb_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_homeMouseExited
        // TODO add your handling code here:
        tb_home.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_homeMouseExited

    private void tb_peopleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_peopleMouseEntered
        // TODO add your handling code here:
        tb_people.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_peopleMouseEntered

    private void tb_budgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_budgetMouseEntered
        // TODO add your handling code here:
        tb_budget.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_budgetMouseEntered

    private void tb_budgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_budgetMouseExited
        // TODO add your handling code here:
        tb_budget.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_budgetMouseExited

    private void tb_officialsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_officialsMouseEntered
        // TODO add your handling code here:
        tb_officials.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_officialsMouseEntered

    private void tb_officialsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_officialsMouseExited
        // TODO add your handling code here:
        tb_officials.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_officialsMouseExited

    private void tb_officialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_officialsActionPerformed
        // TODO add your handling code here:
        Officials frame = new Officials(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_officialsActionPerformed

    private void tb_eventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_eventMouseEntered
        // TODO add your handling code here:
        tb_event.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_eventMouseEntered

    private void tb_eventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_eventMouseExited
        // TODO add your handling code here:
        tb_event.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_eventMouseExited

    private void tb_docMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_docMouseEntered
        // TODO add your handling code here:
        tb_doc.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_docMouseEntered

    private void tb_docMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_docMouseExited
        // TODO add your handling code here:
        tb_doc.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_docMouseExited

    private void tb_logsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_logsMouseEntered
        // TODO add your handling code here:
        tb_logs.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_logsMouseEntered

    private void tb_logsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_logsMouseExited
        // TODO add your handling code here:
        tb_logs.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_logsMouseExited

    private void tb_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_logoutMouseEntered
        // TODO add your handling code here:
        tb_logout.setFont(new java.awt.Font("Tahoma", Font.BOLD, 12));
    }//GEN-LAST:event_tb_logoutMouseEntered

    private void tb_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_logoutMouseExited
        // TODO add your handling code here:
        tb_logout.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12));
    }//GEN-LAST:event_tb_logoutMouseExited

    private void tb_logsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_logsActionPerformed
        // TODO add your handling code here:
        Logs frame = new Logs(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_logsActionPerformed

    private void tb_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_eventActionPerformed
        // TODO add your handling code here:
        Event frame = new Event(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_eventActionPerformed

    private void tb_budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_budgetActionPerformed
        // TODO add yourb_purok handling code here:
        Money frame = new Money(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_budgetActionPerformed

    private void tb_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_docActionPerformed
        // TODO add your handling code here:
        Doc frame = new Doc(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_tb_docActionPerformed

    private void mi_manageaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_manageaccActionPerformed
        // TODO add your handling code here:
        Account frame = new Account(this);
        javax.swing.plaf.InternalFrameUI ui = frame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        frame.setBounds(0, 70, 1010, 570);
        jDesktopPane1.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_mi_manageaccActionPerformed

    private void tb_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_logoutActionPerformed
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_tb_logoutActionPerformed

    private void mi_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_aboutActionPerformed
        // TODO add your handling code here:
        About();
    }//GEN-LAST:event_mi_aboutActionPerformed

    private void mi_changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_changepassActionPerformed
        // TODO add your handling code here:
        UserSetting f = new UserSetting(new javax.swing.JFrame(), true, this);
        f.setLocationRelativeTo(this.a);
        f.setVisible(true);
    }//GEN-LAST:event_mi_changepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mi_about;
    private javax.swing.JMenuItem mi_changepass;
    private javax.swing.JMenuItem mi_help;
    private javax.swing.JMenuItem mi_logout;
    private javax.swing.JMenuItem mi_manageacc;
    private javax.swing.JMenuItem mi_syswiz;
    private javax.swing.JButton tb_budget;
    private javax.swing.JButton tb_doc;
    private javax.swing.JButton tb_event;
    private javax.swing.JButton tb_home;
    private javax.swing.JButton tb_logout;
    private javax.swing.JButton tb_logs;
    private javax.swing.JButton tb_officials;
    private javax.swing.JButton tb_people;
    private javax.swing.JLabel txt_level;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
