/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import DC.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class People extends javax.swing.JInternalFrame {

    Main a;
    DefaultTableModel model1 = new DefaultTableModel();
    int prk;
    String id, ln, fn, mi, brdt, cvst, pstn, occu, rlgn, gndr, cntn;
    Date d;

    /**
     * Creates new form People
     */
    public People() {
        initComponents();
        model1 = (DefaultTableModel) tb_people.getModel();
        LoadPeople();
    }

    public People(Main a) {
        initComponents();
        this.a = a;
        model1 = (DefaultTableModel) tb_people.getModel();
        LoadPeople();

    }

    public void LoadPeople() {
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = c.prepareStatement("SELECT * from people");
            rs = ps.executeQuery();
            model1.setRowCount(0);
            while (rs.next()) {
                model1.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(6)});
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        String x = "";
        for (int i=0; i < model1.getRowCount(); i++){
            x = x + "\n" +(model1.getValueAt(i, 0) + " " + model1.getValueAt(i, 1) + ", " + model1.getValueAt(i, 2));
        }
    }
    void SetNull(){
        id = null;
        ln = null;
        fn = null;
        mi = null;
        brdt = null;
        cvst = null;
        pstn = null;
        occu = null;
        rlgn = null;
        gndr = null;
        cntn = null;
        txt_id.setText("");
        txt_fn.setText("");
        txt_bd.setText("");
        txt_age.setText("");
        txt_gen.setText("");
        txt_stat.setText("");
        txt_prk.setText("");
        txt_pstn.setText("");
        txt_cntn.setText("");
        txt_occu.setText("");
        txt_rlgn.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_people = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        cb_searchfor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_delete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_fn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_bd = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_age = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_stat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_prk = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_pstn = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_cntn = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_gen = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_rlgn = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_occu = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_people.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_people.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last Name", "First Name", "M.I.", "Purok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_people.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_peopleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_people);
        if (tb_people.getColumnModel().getColumnCount() > 0) {
            tb_people.getColumnModel().getColumn(0).setResizable(false);
            tb_people.getColumnModel().getColumn(0).setPreferredWidth(2);
            tb_people.getColumnModel().getColumn(1).setResizable(false);
            tb_people.getColumnModel().getColumn(2).setResizable(false);
            tb_people.getColumnModel().getColumn(3).setResizable(false);
            tb_people.getColumnModel().getColumn(3).setPreferredWidth(2);
            tb_people.getColumnModel().getColumn(4).setResizable(false);
            tb_people.getColumnModel().getColumn(4).setPreferredWidth(2);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 47, 760, 520));

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_searchCaretUpdate(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 180, 20));

        cb_searchfor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb_searchfor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Last Name", "First Name", "Middle Initial", "Purok" }));
        getContentPane().add(cb_searchfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(":");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 10, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Search for");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 70, 20));

        bt_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Remove User Male_20px.png"))); // NOI18N
        bt_delete.setText("DELETE");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Add User Male_20px.png"))); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Change User Male_20px.png"))); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "PEOPLE INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_fn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("NAME");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 20));

        txt_bd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_bd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_bd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BIRTHDATE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        txt_age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 50, 20));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("AGE");
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 50, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CIVIL STATUS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 20));

        txt_stat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_stat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PUROK");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 20));

        txt_prk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_prk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_prk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_prk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("POSITION");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 20));

        txt_pstn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_pstn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_pstn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_pstn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("CONTACT NUMBER");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 20));

        txt_cntn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cntn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_cntn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_cntn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("GENDER");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 20));

        txt_gen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_gen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 20));

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("IDENTIFICATION NUMBER (ID)");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("RELIGION");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 20));

        txt_rlgn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rlgn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_rlgn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_rlgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("OCCUPATION");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 200, 20));

        txt_occu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_occu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_occu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_occu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AddPeople b = new AddPeople(new javax.swing.JFrame(), true, this);
        b.setLocationRelativeTo(this.a);
        b.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tb_peopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_peopleMouseClicked
        // TODO add your handling code here:
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps, ps1, ps2;
            ResultSet rs;
            ps = c.prepareStatement("Select * from people");
            rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString(1).equals(String.valueOf(model1.getValueAt(tb_people.getSelectedRow(), 0)))) {
                    int age;
                    Calendar cal = Calendar.getInstance();
                    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    SimpleDateFormat dt = new SimpleDateFormat("MMMM dd, yyyy");
                    SimpleDateFormat year = new SimpleDateFormat("yyyy");
                    SimpleDateFormat month = new SimpleDateFormat("MM");
                    SimpleDateFormat day = new SimpleDateFormat("dd");

                    try {
                        d = dateFormat.parse(rs.getString(5));
                        age = Integer.parseInt(year.format(cal.getTime())) - Integer.parseInt(year.format(d));
                        txt_bd.setText(dt.format(d));
                        if (Integer.parseInt(month.format(d)) <= Integer.parseInt(month.format(cal.getTime()))) {
                            if (Integer.parseInt(day.format(d)) <= Integer.parseInt(day.format(cal.getTime()))) {
                                txt_age.setText(String.valueOf(age));
                            } else {
                                age--;
                                txt_age.setText(String.valueOf(age));
                            }
                        } else {
                            age--;
                            txt_age.setText(String.valueOf(age));
                        }
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                    ln = rs.getString(2);
                    fn = rs.getString(3);
                    mi = rs.getString(4);
                    txt_fn.setText(rs.getString(3) + " " + rs.getString(4) + " " + rs.getString(2));
                    id = rs.getString(1);
                    txt_id.setText(rs.getString(1));
                    gndr = rs.getString(12);
                    txt_gen.setText(rs.getString(12));
                    cntn = rs.getString(8);
                    txt_cntn.setText(rs.getString(8));
                    rlgn = rs.getString(11);
                    txt_rlgn.setText(rs.getString(11));
                    prk = Integer.parseInt(rs.getString(6));
                    txt_prk.setText("Purok " + rs.getString(6));
                    pstn = rs.getString(7);
                    txt_pstn.setText(rs.getString(7));
                    cvst = rs.getString(9);
                    txt_stat.setText(rs.getString(9));
                    occu = rs.getString(10);
                    txt_occu.setText(rs.getString(10));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tb_peopleMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (this.id==null) {
            JOptionPane.showMessageDialog(this, "Sorry! You have not select one of the people in the table.", "Update People", JOptionPane.ERROR_MESSAGE);
        } else {
            UpdatePeople c = new UpdatePeople(new javax.swing.JFrame(), true, this);
            c.setLocationRelativeTo(this.a);
            c.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        if (this.id==null) {
            JOptionPane.showMessageDialog(this, "Sorry! You have not select one of the people in the table.", "Delete People", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                DBConnection.init();
                Connection c = (Connection) DBConnection.getConnection();
                PreparedStatement ps, ps1;
                ps = c.prepareStatement("Delete from people where id=(?)");
                ps.setString(1, id);
                ps1 = c.prepareStatement("INSERT INTO logs (user,lvl,actn,dati,info) VALUES" + "('" + this.a.a.getUser() + "','" +this.a.a.getLevel()+ "','Delete People',DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S'), 'The user deleted people named " + txt_fn.getText() + "[" + txt_id.getText() + "] to the system.')");
                int n = JOptionPane.showConfirmDialog(null, "Do you want to delete this people?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    ps.executeUpdate();
                    ps1.execute();
                    JOptionPane.showMessageDialog(null, "You delete this people successfully");
                    LoadPeople();
                    SetNull();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void txt_searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_searchCaretUpdate
        // TODO add your handling code here:
        String x = (String) cb_searchfor.getSelectedItem();
        String y = null;
        if ("ID".equals(x)) {
            y = "ID";
        } else if ("First Name".equals(x)) {
            y = "fn";
        } else if ("Last Name".equals(x)) {
            y = "ln";
        } else if ("Middle Initial".equals(x)) {
            y = "mi";
        } else if ("Purok".equals(x)) {
            y = "prk";
        } else {
        }
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = c.prepareStatement("SELECT * from people WHERE " + y + " LIKE '%" + txt_search.getText() + "%'");
            rs = ps.executeQuery();
            model1.setRowCount(0);
            while (rs.next()) {
                model1.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(6)});
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txt_searchCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_delete;
    private javax.swing.JComboBox<String> cb_searchfor;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_people;
    private javax.swing.JLabel txt_age;
    private javax.swing.JLabel txt_bd;
    private javax.swing.JLabel txt_cntn;
    private javax.swing.JLabel txt_fn;
    private javax.swing.JLabel txt_gen;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_occu;
    private javax.swing.JLabel txt_prk;
    private javax.swing.JLabel txt_pstn;
    private javax.swing.JLabel txt_rlgn;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_stat;
    // End of variables declaration//GEN-END:variables
}
