/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import DC.DBConnection;
import java.awt.Image;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XtianDR
 */
public class UpdateOfficials extends javax.swing.JDialog {
    Officials a;
    String id;
    Date date = new Date ();
    Image img = (new ImageIcon(getClass().getResource("/Misc/null.png"))).getImage();

    
    public UpdateOfficials(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public UpdateOfficials(java.awt.Frame parent, boolean modal, Officials a) {
        super(parent, modal);
        initComponents();
        this.a = a;
        
        
    }
    
    void LoadOfficials(){
        if (cb_officials.getSelectedIndex()==1){
            id = "KPTN";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==2){
            id = "KGWD1";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==3){
            id = "KGWD2";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==4){
            id = "KGWD3";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==5){
            id = "KGWD4";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==6){
            id = "KGWD5";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==7){
            id = "KGWD6";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==8){
            id = "KGWD7";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==9){
            id = "SECR";
            SetField(true);
        } else if (cb_officials.getSelectedIndex()==10){
            id = "TREA";
            SetField(true);
        } else {
            SetField(false);
        }
    }
    void GetData(String id){
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = c.prepareStatement("SELECT * from officials");
            rs = ps.executeQuery();
            while (rs.next()) {
                if (rs.getString(1).equals(id)){
                    txt_ln.setText(rs.getString(2));
                    txt_fn.setText(rs.getString(3));
                    txt_mi.setText(rs.getString(4));
                    cb_gender.setSelectedItem(rs.getString(8));
                    cb_cs.setSelectedItem(rs.getString(7));
                    
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void SetField(boolean x){
        bt_update.setEnabled(x);
        txt_ln.setEnabled(x);
        txt_fn.setEnabled(x);
        txt_mi.setEnabled(x);
        txt_bday.setEnabled(x);
        cb_prk.setEnabled(x);
        cb_cs.setEnabled(x);
        cb_gender.setEnabled(x);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_officials = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_mi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_fn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ln = new javax.swing.JTextField();
        cb_cs = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_gender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_bday = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cb_prk = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        bt_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Event");
        setIconImage(img);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_officials.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_officials.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT OFFICIALS/STAFF--", "Punong Barangay", "1st Kagawad", "2nd Kagawad", "3rd Kagawad", "4th Kagawad", "5th Kagawad", "6th Kagawad", "7th Kagawad", "Secretary", "Treasurer" }));
        cb_officials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_officialsActionPerformed(evt);
            }
        });
        jPanel1.add(cb_officials, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 330, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("BIRTH DATE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("POSITION:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        txt_mi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_mi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("M. I.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, -1));

        txt_fn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 130, -1));

        txt_ln.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        cb_cs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_cs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widow" }));
        jPanel1.add(cb_cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NAME:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 20));

        cb_gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Gay", "Lesbian" }));
        jPanel1.add(cb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("GENDER:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));
        jPanel1.add(txt_bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PUROK LEAD:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 20));

        cb_prk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Purok 1", "Purok 2", "Purok 3", "Purok 4", "Purok 5", "Purok 6", "Purok 7" }));
        jPanel1.add(cb_prk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CIVIL STATUS:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 100, 20));

        bt_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Ok_20px.png"))); // NOI18N
        bt_update.setText("UPDATE");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });
        jPanel1.add(bt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Cancel_20px.png"))); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
       String p;
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       if (cb_officials.getSelectedIndex() == 0 || cb_officials.getSelectedIndex() == 1 || cb_officials.getSelectedIndex() == 9 || cb_officials.getSelectedIndex() == 10){
           p = (String) cb_officials.getSelectedItem();
       } else {
           p = "Kagawad";
       }
        try {
                DBConnection.init();
                Connection c = (Connection) DBConnection.getConnection();
                PreparedStatement ps, ps1;
                ps = c.prepareStatement("Update officials set id =(?), ln =(?), fn =(?), mi =(?), pstn =(?), prk =(?), cvst =(?), gndr =(?), bday =(?) where id like (?)");
                ps.setString(1, id);
                ps.setString(2, txt_ln.getText());
                ps.setString(3, txt_fn.getText());
                ps.setString(4, txt_mi.getText());
                ps.setString(5, p);
                ps.setString(6, String.valueOf(cb_prk.getSelectedIndex()));
                ps.setString(7, (String) cb_cs.getSelectedItem());
                ps.setString(8, (String) cb_gender.getSelectedItem());
                ps.setString(9, dateFormat.format(this.txt_bday.getDate()));
                ps.setString(10, id);
                ps1 = c.prepareStatement("INSERT INTO logs (user,lvl,actn,dati,info) VALUES" + "('" + this.a.a.a.getUser() + "','" +this.a.a.a.getLevel()+ "','Update Official',DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S'), 'The user updated the official to the system.\nID: " + this.id + "\nName: " + txt_fn.getText() + " " + txt_mi.getText() + " " + txt_ln.getText() + "')");
                int n = JOptionPane.showConfirmDialog(this, "Do you want to update this official", "Confirm Update", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    ps.executeUpdate();
                    ps1.execute();
                    JOptionPane.showMessageDialog(this, "You update the official successfully");
                    dispose();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_bt_updateActionPerformed

    private void cb_officialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_officialsActionPerformed
        // TODO add your handling code here:
        LoadOfficials();
        GetData(id);
    }//GEN-LAST:event_cb_officialsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateOfficials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateOfficials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateOfficials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateOfficials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateOfficials dialog = new UpdateOfficials(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_update;
    private javax.swing.JComboBox<String> cb_cs;
    private javax.swing.JComboBox<String> cb_gender;
    private javax.swing.JComboBox<String> cb_officials;
    private javax.swing.JComboBox<String> cb_prk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txt_bday;
    private javax.swing.JTextField txt_fn;
    private javax.swing.JTextField txt_ln;
    private javax.swing.JTextField txt_mi;
    // End of variables declaration//GEN-END:variables
}
