/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

import DC.DBConnection;
import java.awt.Image;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author XtianDR
 */
public class UpdateEvent extends javax.swing.JDialog {
    Event a;
    Date date = new Date ();
    Image img = (new ImageIcon(getClass().getResource("/Misc/null.png"))).getImage();

    public UpdateEvent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        LoadEvent();
        txt_desc.setLineWrap(true);
        txt_desc.setWrapStyleWord(true);
    }
    public UpdateEvent(java.awt.Frame parent, boolean modal, Event a) {
        super(parent, modal);
        initComponents();
        this.a = a;
        LoadEvent();
        txt_desc.setLineWrap(true);
        txt_desc.setWrapStyleWord(true);
    }
    
    boolean checkConflict(String id, String start, String end){
        int count = 0;
        try {
            DBConnection.init();
            Connection c = (Connection) DBConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            ps = c.prepareStatement("SELECT * FROM events WHERE ((ev_start <= '" + start + "' AND ev_end > '" + start + "') OR (ev_start < '" + end + "' AND ev_end >= '" + end + "')) AND ID !="+id+"");
            rs = ps.executeQuery();
            while (rs.next()) {
                count++;
            }
            System.out.println(count);
        } catch (Exception e) {
            System.out.println(e);
        }
        return count != 0;
    }
    
    void LoadEvent(){
        txt_title.setText(a.tl);
        txt_desc.setText(a.ds);
        DateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
        DateFormat timeFormat = new SimpleDateFormat("hh:mm a");
        try {
            Date dt = dateFormat.parse(a.da);
            Date start = timeFormat.parse(a.st);
            Date end = timeFormat.parse(a.en);
            txt_date.setDate(dt);
            txt_start.setValue(start);
            txt_end.setValue(end);
        } catch (ParseException e) {
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_end = new javax.swing.JSpinner(new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY));
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_start = new javax.swing.JSpinner(new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY));
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_w = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Event");
        setIconImage(img);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Event Title:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        txt_title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 320, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Time:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 40, 20));

        txt_desc.setColumns(20);
        txt_desc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_desc.setRows(5);
        jScrollPane1.setViewportView(txt_desc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 320, 140));

        txt_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Desciption:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        JSpinner.DateEditor de = new JSpinner.DateEditor(txt_end,"h:mm a");
        txt_end.setEditor(de);
        txt_end.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setText("(Start)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 40, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setText("(End)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 40, 20));

        txt_start.setEditor(new JSpinner.DateEditor(txt_start,"h:mm a"));
        txt_start.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 90, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Cancel_20px.png"))); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 110, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/Ok_20px.png"))); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 80, 30));

        txt_w.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txt_w.setForeground(java.awt.Color.red);
        jPanel1.add(txt_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date st = new Date();
        Date en =  new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        String start = (String) dateFormat.format(this.txt_date.getDate()) + " " + (String) timeFormat.format(this.txt_start.getValue());
        String end = (String) dateFormat.format(this.txt_date.getDate()) + " " + (String) timeFormat.format(this.txt_end.getValue());
        DateFormat dF = new SimpleDateFormat("HH:mm:ss");
        try {
            st = dF.parse((String) timeFormat.format(this.txt_start.getValue()));
            en = dF.parse((String) timeFormat.format(this.txt_end.getValue()));
        } catch (ParseException e) {
            System.out.println(e);
        }
        if (txt_title.getText().isEmpty()){
            txt_w.setText("*Title is required");
        } else if (st.after(en) || st.equals(en)){
            txt_w.setText("*Invalid time schedule");
        } else if (checkConflict(this.a.id,start, end)){
            JOptionPane.showMessageDialog(this, "Sorry! Their is a conflict of schedule in the events.", "Event Conflict", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                DBConnection.init();
                Connection c = (Connection) DBConnection.getConnection();
                PreparedStatement ps, ps1;
                ps = c.prepareStatement("Update events set ID =(?), ev_name =(?), ev_desc =(?), ev_start =(?), ev_end =(?), ev_perm =(?) where ID like (?)");
                ps.setString(1, this.a.id);
                ps.setString(2, txt_title.getText());
                ps.setString(3, txt_desc.getText());
                ps.setString(4, start);
                ps.setString(5, end);
                ps.setString(6, this.a.a.a.getName());
                ps.setString(7, this.a.id);
                ps1 = c.prepareStatement("INSERT INTO logs (user,lvl,actn,dati,info) VALUES" + "('" + this.a.a.a.getUser() + "','" +this.a.a.a.getLevel()+ "','Update Event',DATE_FORMAT(NOW(),'%Y-%m-%d %H:%i:%S'), 'The user updated event to the system.')");
                int n = JOptionPane.showConfirmDialog(this, "Do you want to update this event?", "Confirm Add", JOptionPane.YES_NO_OPTION);
                if (n == 0) {
                    ps.executeUpdate();
                    ps1.execute();
                    JOptionPane.showMessageDialog(this, "Event Added!");
                    dispose();
                    this.a.LoadEvents();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateEvent dialog = new UpdateEvent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JSpinner txt_end;
    private javax.swing.JSpinner txt_start;
    private javax.swing.JTextField txt_title;
    private javax.swing.JLabel txt_w;
    // End of variables declaration//GEN-END:variables
}
